spring:
  datasource:
    url: jdbc:mysql://localhost:3307/project_si_db
    username: project_user
    password: project_password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
